on: [pull_request]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_OWNER: "GradientFlow-ai"
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github
      - run: aws sts get-caller-identity

      - name: Decrypt secrets
        run: |
          echo "${{ secrets.MY_PGP_PRIVATE_KEY }}" | base64 --decode > sops-secret.asc
          echo "${{ secrets.MY_PGP_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 -o passphrase.txt
          sops -d secrets.yaml --pgp sops-secret.asc > decryptsecrets.yaml

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var-file=decryptsecrets.yaml
