name: Terraform Apply

on: [issue_comment]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform apply') }}
    runs-on: ubuntu-latest
    name: Apply approved plan
    env:
      GITHUB_OWNER: "GradientFlow-ai"
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt

      - name: Import GPG key
        run: |
          echo "${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}" | gpg --import --batch
        env:
          ACTIONS_GPG_PRIVATE_KEY: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}

      - name: Unlock encrypted files with git-crypt
        run: git-crypt unlock

      - name: terraform apply
        uses: dflook/terraform-apply@v1

      - name: Commit and push updated state file
        uses: stefanzweifel/git-auto-commit-action@v4

