name: Terraform Apply

on: [issue_comment]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform apply') }}
    runs-on: ubuntu-latest
    name: Apply approved plan
    env:
      GITHUB_OWNER: "GradientFlow-ai"
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Install git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt

      - name: Import GPG key
        run: |
          echo "${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}" | gpg --import --batch
        env:
          ACTIONS_GPG_PRIVATE_KEY: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}

      - name: Unlock encrypted files with git-crypt
        run: git-crypt unlock

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github
      - run: aws sts get-caller-identity

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          variables: |
            TF_VAR_AWS_ACCESS_KEY_ID = "${{ secrets.AWS_ACCESS_KEY_ID }}"
            TF_VAR_AWS_SECRET_ACCESS_KEY = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            TF_VAR_VERCEL_API_TOKEN = "${{ secrets.VERCEL_API_KEY }}"
