name: Terraform Apply

on: [issue_comment]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  apply:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, 'terraform apply') }}
    runs-on: ubuntu-latest
    name: Apply approved plan
    env:
      GITHUB_OWNER: "GradientFlow-ai"
      GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      TERRAFORM_ACTIONS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.issue.number }}/merge

      - name: Install git-crypt
        run: |
          sudo apt-get update
          sudo apt-get install -y git-crypt

      - name: Import GPG key
        run: |
          echo "${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}" | gpg --import --batch
        env:
          ACTIONS_GPG_PRIVATE_KEY: ${{ secrets.ACTIONS_GPG_PRIVATE_KEY }}

      - name: Unlock encrypted files with git-crypt
        run: git-crypt unlock

      - name: terraform apply
        uses: dflook/terraform-apply@v1

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit updated state file
        run: |
          git add *.tfstate
          git commit -m "Update Terraform state file"

      - name: Push updated state file
        run: |
          git push origin HEAD:refs/heads/${{ github.event.issue.pull_request.head.ref }}
